[build]
  command = "npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"

[functions]
  # No version here, it's handled by NODE_VERSION in environment

[[plugins]]
  package = "@netlify/plugin-nextjs"
